### ISSUE TITLE
[ERROR] cours create (NoMethodError) "undefined method `places' for nil:NilClass"

### ISSUE THREAD

**Issue by philippe-nougaillon** [philippe-nougaillon/Planning_IAE#19]
A NoMethodError occurred in cours#create:

  undefined method `places' for nil:NilClass
  app/models/cour.rb:584:in `check_chevauchement'

**Comment by philippe-nougaillon** [comment]
A NoMethodError occurred in cours#create:

  undefined method `places' for nil:NilClass
  app/models/cour.rb:584:in `check_chevauchement'


-------------------------------
Request:
-------------------------------

  * URL        : http://planning.iae-paris.com/cours
  * HTTP Method: POST
  * IP address : 194.214.30.192
  * Parameters : {"authenticity_token"=>"MVqxbxiE0qg3vBxKf8bbk08EV4ifs7QId9v27eLlUDsb282+rsYfWU16rf//kq3qm9fbfeemuaj9G3vG3iquuQ==", "from"=>"occupation", "id"=>"", "cour"=>{"debut"=>"2021-06-28T10:00", "duree"=>"3.0", "formation_id"=>"23", "intervenant_id"=>"179", "intervenant_binome_id"=>"", "ue"=>"", "nom"=>"", "hors_service_statutaire"=>"0", "elearning"=>"0", "salle_id"=>"Salle ou intervenant pas disponible", "commentaires"=>""}, "commit"=>"Enregistrer", "controller"=>"cours", "action"=>"create"}
  * Timestamp  : 2021-06-28 06:47:00 UTC
  * Server : bfeb13e9-22a9-41fe-a999-2393db81d722
    * Rails root : /app
  * Process: 4
