### ISSUE TITLE
[ERROR] salles libres (NoMethodError) "undefined method `<=' for nil:NilClass"

### ISSUE THREAD

**Issue by philippe-nougaillon** [philippe-nougaillon/Planning_IAE#89]
A NoMethodError occurred in salles#libres:

  undefined method `<=' for nil:NilClass
  app/models/cour.rb:576:in `reservation_dates_must_make_sense'

-------------------------------
Request:
-------------------------------

  * URL        : http://planning.iae-paris.com/salles/libres.json?date=2022-07-05T12:30&id=&duree=&formation_id=23&intervenant_id=167
  * HTTP Method: GET
  * IP address : 194.214.30.206
  * Parameters : {"date"=>"2022-07-05T12:30", "id"=>"", "duree"=>"", "formation_id"=>"23", "intervenant_id"=>"167", "controller"=>"salles", "action"=>"libres", "format"=>"json"}
  * Timestamp  : 2021-07-15 13:02:24 UTC
  * Server : 61f825c8-a8b4-4112-926d-847266b4b333
    * Rails root : /app
  * Process: 4

-------------------------------
Session:
-------------------------------

  * session id: "05cddc4a608f54a09c1c373f1760c1a8"
  * data: {"session_id"=>"05cddc4a608f54a09c1c373f1760c1a8",
   "page_slide"=>2,
   "view"=>"list",
   "filter"=>"upcoming",
   "paginate"=>"pages",
   "start_date"=>"2021-09-21",
   "warden.user.user.key"=>[[35], "$2a$10$8cUTMrZ7jhlsmcmi6p5cRe"],
   "_csrf_token"=>"rFb2/XUNcVS84Pk4o9ePVQcf32zdSMGHNXEpqxHjYLo=",
   "formation"=>"IAE",
   "intervenant"=>"",
   "ue"=>"",
   "etat"=>""}

-------------------------------
Environment:
-------------------------------

  * CONTENT_TYPE                                            : application/x-www-form-urlencoded; charset=UTF-8
    * GATEWAY_INTERFACE                                       : CGI/1.2
    * HTTP_ACCEPT                                             : */*
    * HTTP_ACCEPT_ENCODING                                    : gzip, deflate
    * HTTP_ACCEPT_LANGUAGE                                    : fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    * HTTP_CONNECTION                                         : close
    * HTTP_CONNECT_TIME                                       : 0
    * HTTP_COOKIE                                             : _session_id=c0VwYJLxk4J1DcqIHCoCwzM4QYcsKj76VKAl9VPKK5LDRe4%2BxVACtlfDpo1zLdvAG%2BnIgTE%2FaWx6CA5HYNQ3MJxB3mGA3KP1kZ2Wq7UbRw%2BKrP9pPTTd%2FcmvLHcUGLcUBDbGgFyRtd1te2Rh7CJCXllFGjkH9DKPQX3a2bCNof4vfknS58qY3WyjGVDycO6cqPq5orcyHGQf%2B1hlDFieNekyCgNQYXFQFnMaKfgZwzeI4Rytf7Yh6Dv849riy32bUSxUoge6EohskuYMXLl5%2BUuAp00BhWuAixIiGyx0hdO4qKCdJJij%2FokTRyafxf7uasnZGNWnasHogI6ra1qvYYktCtz%2BxtxiuvRc3mD14LkDmZDXztSegY5cHTN0KB6d%2BPRRCCaTnul%2FEJZAcB6bRPeCnxBz0S7TadQt5ara6Wr9YONWyG1YcZgGDaN3H5alJZ2GIcL97wzRtezz91nWWaxD%2F3GKU0whq7x7mF7KWiLPhkcKrr0xx4Mj8BRsKv%2BRQupfp%2BkEimtoNyBhRHi046T71hSK4JgXRgvo0sH3F6E84bQ5RAlnq8%2FfsbGHriV7MTeLWCZOJguKmCE3ItQmuBMwZMX7f7HKkr5V0FRkqS8NzhlSyUBDgdz0GI2N0BJd8EjDvs2FtRPnA%2FCagqtJDlX7ND9NGuTNiUBHc6w5cRgB--DsDYIraQKn41osMj--gRcN2C1Z6dARJvO3a1gIdA%3D%3D; _ga=GA1.2.1537639217.1626329547; _gid=GA1.2.790831031.1626329547
    * HTTP_HOST                                               : planning.iae-paris.com
    * HTTP_REFERER                                            : http://planning.iae-paris.com/cours/new?debut=2021-07-15T13%3A00%3A39%2B00%3A00&formation=IAE
    * HTTP_TOTAL_ROUTE_TIME                                   : 0
    * HTTP_USER_AGENT                                         : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
    * HTTP_VERSION                                            : HTTP/1.1
    * HTTP_VIA                                                : 1.1 vegur
    * HTTP_X_CSRF_TOKEN                                       : ksntNM/lgxTDIQMAaOqUGXqP7ks1TPDqc0XVeX2rzJT/EyWgq/wA+O3wzg+8pOAF0kuexEETi2lZffD6qI30ug==
    * HTTP_X_FORWARDED_FOR                                    : 194.214.30.206
    * HTTP_X_FORWARDED_PORT                                   : 80
    * HTTP_X_FORWARDED_PROTO                                  : http
    * HTTP_X_REQUESTED_WITH                                   : XMLHttpRequest
    * HTTP_X_REQUEST_ID                                       : 37c1b361-1031-416f-8c4a-379e19c656a0
    * HTTP_X_REQUEST_START                                    : 1626354144592
    * ORIGINAL_FULLPATH                                       : /salles/libres.json?date=2022-07-05T12:30&id=&duree=&formation_id=23&intervenant_id=167
    * ORIGINAL_SCRIPT_NAME                                    :
    * PATH_INFO                                               : /salles/libres.json
    * QUERY_STRING                                            : date=2022-07-05T12:30&id=&duree=&formation_id=23&intervenant_id=167
    * REMOTE_ADDR                                             : 10.1.18.91
    * REQUEST_METHOD                                          : GET
    * REQUEST_PATH                                            : /salles/libres.json
    * REQUEST_URI                                             : /salles/libres.json?date=2022-07-05T12:30&id=&duree=&formation_id=23&intervenant_id=167
    * ROUTES_14300_SCRIPT_NAME                                :
    * SCRIPT_NAME                                             :
    * SERVER_NAME                                             : planning.iae-paris.com
    * SERVER_PORT                                             : 80
    * SERVER_PROTOCOL                                         : HTTP/1.1
    * SERVER_SOFTWARE                                         : puma 4.3.8 Mysterious Traveller
    * action_controller.instance                              : #<SallesController:0x00007f17d64a1a88>
    * action_dispatch.authenticated_encrypted_cookie_salt     : authenticated encrypted cookie
    * action_dispatch.backtrace_cleaner                       : #<Rails::BacktraceCleaner:0x000055fcf12373e8>
    * action_dispatch.content_security_policy                 :
    * action_dispatch.content_security_policy_nonce_directives:
    * action_dispatch.content_security_policy_nonce_generator :
    * action_dispatch.content_security_policy_report_only     : false
    * action_dispatch.cookies                                 : #<ActionDispatch::Cookies::CookieJar:0x00007f17d64ca0c8>
    * action_dispatch.cookies_digest                          :
    * action_dispatch.cookies_rotations                       : #<ActiveSupport::Messages::RotationConfiguration:0x000055fceeb6ff58>
    * action_dispatch.cookies_same_site_protection            : #<Proc:0x000055fcf2fc3b50 /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/application.rb:629>
    * action_dispatch.cookies_serializer                      : json
    * action_dispatch.encrypted_cookie_cipher                 :
    * action_dispatch.encrypted_cookie_salt                   : encrypted cookie
    * action_dispatch.encrypted_signed_cookie_salt            : signed encrypted cookie
    * action_dispatch.http_auth_salt                          : http authentication
    * action_dispatch.key_generator                           : #<ActiveSupport::CachingKeyGenerator:0x000055fcf3269850>
    * action_dispatch.logger                                  : #<ActiveSupport::Logger:0x000055fceec99190>
    * action_dispatch.parameter_filter                        : [:password]
    * action_dispatch.permissions_policy                      :
    * action_dispatch.redirect_filter                         : []
    * action_dispatch.remote_ip                               : 194.214.30.206
    * action_dispatch.request.content_type                    : application/x-www-form-urlencoded
    * action_dispatch.request.formats                         : [#<Mime::Type:0x000055fceea9f998 @synonyms=["text/x-json", "application/jsonrequest"], @symbol=:json, @string="application/json", @hash=-2113649960876245115>]
    * action_dispatch.request.parameters                      : {"date"=>"2022-07-05T12:30", "id"=>"", "duree"=>"", "formation_id"=>"23", "intervenant_id"=>"167", "controller"=>"salles", "action"=>"libres", "format"=>"json"}
    * action_dispatch.request.path_parameters                 : {:controller=>"salles", :action=>"libres", :format=>"json"}
    * action_dispatch.request.query_parameters                : {"date"=>"2022-07-05T12:30", "id"=>"", "duree"=>"", "formation_id"=>"23", "intervenant_id"=>"167"}
    * action_dispatch.request.request_parameters              : {}
    * action_dispatch.request.unsigned_session_cookie         : {"session_id"=>"05cddc4a608f54a09c1c373f1760c1a8", "page_slide"=>2, "view"=>"list", "filter"=>"upcoming", "paginate"=>"pages", "start_date"=>"2021-09-21", "warden.user.user.key"=>[[35], "$2a$10$8cUTMrZ7jhlsmcmi6p5cRe"], "_csrf_token"=>"rFb2/XUNcVS84Pk4o9ePVQcf32zdSMGHNXEpqxHjYLo=", "formation"=>"IAE...
    * action_dispatch.request_id                              : 37c1b361-1031-416f-8c4a-379e19c656a0
    * action_dispatch.routes                                  : #<ActionDispatch::Routing::RouteSet:0x000055fcf29d1350>
    * action_dispatch.secret_key_base                         : d32ed58262eb5e7a69dc44de68438385b623cfbedeaec283ac06bf15529df6243d542ca99e152642fc36db48ecae5d64b47292cf5cea7192e95d52469b728983
    * action_dispatch.show_detailed_exceptions                : false
    * action_dispatch.show_exceptions                         : true
    * action_dispatch.signed_cookie_digest                    :
    * action_dispatch.signed_cookie_salt                      : signed cookie
    * action_dispatch.use_authenticated_cookie_encryption     : true
    * action_dispatch.use_cookies_with_metadata               : true
    * puma.config                                             : #<Puma::Configuration:0x000055fcee229c78>
    * puma.request_body_wait                                  : 0
    * puma.socket                                             : #<TCPSocket:0x00007f17d6491700>
    * rack.after_reply                                        : []
    * rack.cors                                               : #<Rack::Cors::Result:0x00007f17d6490b48>
    * rack.errors                                             : #<IO:0x000055fcedb27768>
    * rack.hijack                                             : #<Puma::Client:0x00007f17d64916d8>
    * rack.hijack?                                            : true
    * rack.input                                              : #<Puma::NullIO:0x000055fcee58a930>
    * rack.multiprocess                                       : false
    * rack.multithread                                        : true
    * rack.request.cookie_hash                                : {"_session_id"=>"c0VwYJLxk4J1DcqIHCoCwzM4QYcsKj76VKAl9VPKK5LDRe4+xVACtlfDpo1zLdvAG+nIgTE/aWx6CA5HYNQ3MJxB3mGA3KP1kZ2Wq7UbRw+KrP9pPTTd/cmvLHcUGLcUBDbGgFyRtd1te2Rh7CJCXllFGjkH9DKPQX3a2bCNof4vfknS58qY3WyjGVDycO6cqPq5orcyHGQf+1hlDFieNekyCgNQYXFQFnMaKfgZwzeI4Rytf7Yh6Dv849riy32bUSxUoge6EohskuYMXLl5+UuAp00...
    * rack.request.cookie_string                              : _session_id=c0VwYJLxk4J1DcqIHCoCwzM4QYcsKj76VKAl9VPKK5LDRe4%2BxVACtlfDpo1zLdvAG%2BnIgTE%2FaWx6CA5HYNQ3MJxB3mGA3KP1kZ2Wq7UbRw%2BKrP9pPTTd%2FcmvLHcUGLcUBDbGgFyRtd1te2Rh7CJCXllFGjkH9DKPQX3a2bCNof4vfknS58qY3WyjGVDycO6cqPq5orcyHGQf%2B1hlDFieNekyCgNQYXFQFnMaKfgZwzeI4Rytf7Yh6Dv849riy32bUSxUoge6EohskuYMXLl5%2BUuAp00BhWuAixIiGyx0hdO4qKCdJJij%2FokTRyafxf7uasnZGNWnasHogI6ra1qvYYktCtz%2BxtxiuvRc3mD14LkDmZDXztSegY5cHTN0KB6d%2BPRRCCaTnul%2FEJZAcB6bRPeCnxBz0S7TadQt5ara6Wr9YONWyG1YcZgGDaN3H5alJZ2GIcL97wzRtezz91nWWaxD%2F3GKU0whq7x7mF7KWiLPhkcKrr0xx4Mj8BRsKv%2BRQupfp%2BkEimtoNyBhRHi046T71hSK4JgXRgvo0sH3F6E84bQ5RAlnq8%2FfsbGHriV7MTeLWCZOJguKmCE3ItQmuBMwZMX7f7HKkr5V0FRkqS8NzhlSyUBDgdz0GI2N0BJd8EjDvs2FtRPnA%2FCagqtJDlX7ND9NGuTNiUBHc6w5cRgB--DsDYIraQKn41osMj--gRcN2C1Z6dARJvO3a1gIdA%3D%3D; _ga=GA1.2.1537639217.1626329547; _gid=GA1.2.790831031.1626329547
    * rack.request.form_hash                                  : {}
    * rack.request.form_input                                 : #<Puma::NullIO:0x000055fcee58a930>
    * rack.request.form_vars                                  : [FILTERED]
    * rack.request.query_hash                                 : {"date"=>"2022-07-05T12:30", "id"=>"", "duree"=>"", "formation_id"=>"23", "intervenant_id"=>"167"}
    * rack.request.query_string                               : date=2022-07-05T12:30&id=&duree=&formation_id=23&intervenant_id=167
    * rack.run_once                                           : false
    * rack.session                                            : #<ActionDispatch::Request::Session:0x00007f17d64a2ca8>
    * rack.session.options                                    : #<ActionDispatch::Request::Session::Options:0x00007f17d64a2c58>
    * rack.tempfiles                                          : []
    * rack.url_scheme                                         : http
    * rack.version                                            : [1, 3]
    * warden                                                  : Warden::Proxy:3129900 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x000055fcf21d6f10>}

-------------------------------
Backtrace:
-------------------------------

  app/models/cour.rb:576:in `reservation_dates_must_make_sense'
  app/controllers/salles_controller.rb:176:in `block in libres'
  app/controllers/salles_controller.rb:174:in `libres'

**Comment by philippe-nougaillon** [comment]
ajout d'un test dans Cour.reservation_dates_must_make_sense pour éviter une comparaison avec nil
