### ISSUE TITLE
[ERROR] salles libres (Date::Error) "invalid date"

### ISSUE THREAD

**Issue by philippe-nougaillon** [philippe-nougaillon/Planning_IAE#91]
A Date::Error occurred in salles#libres:

  invalid date
  app/controllers/salles_controller.rb:167:in `parse'

-------------------------------
Request:
-------------------------------

  * URL        : https://planning.iae-paris.com/salles/libres.json?date=2022-001-21T09:00&id=&duree=4.0&formation_id=464&intervenant_id=445
  * HTTP Method: GET
  * IP address : 194.214.30.201
  * Parameters : {"date"=>"2022-001-21T09:00", "id"=>"", "duree"=>"4.0", "formation_id"=>"464", "intervenant_id"=>"445", "controller"=>"salles", "action"=>"libres", "format"=>"json"}
  * Timestamp  : 2021-07-15 09:53:38 UTC
  * Server : 61f825c8-a8b4-4112-926d-847266b4b333
    * Rails root : /app
  * Process: 4

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"d4df56b4a7012523a73aa985a0a1e623",
   "view"=>"list",
   "filter"=>"all",
   "paginate"=>"all",
   "start_date"=>"2021-07-15",
   "warden.user.user.key"=>[[45], "$2a$10$5c0vO4sO1DmxkQPRxg47n."],
   "_csrf_token"=>"cfkNzdrEJAUeznyG4YScM564sMhME3cKmNjKGiOdDYI=",
   "formation"=>"MAE JB 2021 2022 GROUPE 2",
   "intervenant"=>"",
   "ue"=>"",
   "etat"=>""}

-------------------------------
Environment:
-------------------------------

  * CONTENT_TYPE                                            : application/x-www-form-urlencoded; charset=UTF-8
    * GATEWAY_INTERFACE                                       : CGI/1.2
    * HTTP_ACCEPT                                             : */*
    * HTTP_ACCEPT_ENCODING                                    : gzip, deflate, br
    * HTTP_ACCEPT_LANGUAGE                                    : fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    * HTTP_CONNECTION                                         : close
    * HTTP_CONNECT_TIME                                       : 0
    * HTTP_COOKIE                                             : _session_id=LcVuHYzNVUSmULOzBCKSXShqYZ4TLAszNyopHfkoJ27dTrUk5FL7ZQRigdxH%2BmUl8%2BTYdMQLL5OeGrZS8Y1hliznC%2B7o7fMbb%2FZFboTiVzyWccehL3cp3tDLTw9KHxVF9dVOhTOJXjG3GCE82JBqBskC0NNQDlI7kY%2FQDxhRxHE%2Bbt9rxGGoF9f73skWH02bHSBbJqKUJ93VUopKR8ewL8E8mQyVFfuzMxDKxBHnsu29o5e9KfZW6LBhtD4TH7MTj%2Fy3gRJST%2BasmGBQOagTr4t7KFaUjl6XPbgcICwR2%2FwkbjINsnibanTfBNs6vmpl2nI8%2FH0IvHRaHAVK0isX94fxnPPvObWrjrBK4aqFxr12pth3hwO8ok0m6qoaf31dkENCKSZVuyciBste1ShMBn3k5Oi1RaFqLrqbR3fl1OOFlH0rzubPH0uJuX3Xy0zGz%2FWgi3XRXKicXjIL%2Bt9Qcm%2F3fKSFyKT8Ueu92SrStYP82meIGyWm1bM66m%2BllwBGyfyWQZQ8kJehpFJ0A4khHCMbdZxg345W9sC54t7YAuwz7282fkz0wJwLjwv0FWLQTwMlaTm6PZdoptrh1UkKAKlIc%2BxmZRz9cLsApm45%2Fct4MGOGKsS9aBocvWq6BOCm0ghukh5nteSHuNXzWXlpyXFoX47KnDXrLWgw3blmDN8e--eCYg0PdM0%2FBXDCff--JBz3gHrieMDdewRBkpIShA%3D%3D; _ga=GA1.2.2089818695.1626342699; _gid=GA1.2.816376150.1626342699
    * HTTP_HOST                                               : planning.iae-paris.com
    * HTTP_REFERER                                            : https://planning.iae-paris.com/cours/new?debut=2021-07-15T09%3A52%3A30%2B00%3A00&formation=MAE+JB+2021+2022+GROUPE+2
    * HTTP_TOTAL_ROUTE_TIME                                   : 0
    * HTTP_USER_AGENT                                         : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
    * HTTP_VERSION                                            : HTTP/1.1
    * HTTP_VIA                                                : 1.1 vegur
    * HTTP_X_CSRF_TOKEN                                       : IkhlQAXIejI+46ar18r0wrXFVysr2Hn+qXJuZ5zaiWo4JlvQ+taPtCdSzs56joPp4ETfSWKE6cKbq8mqY1AygQ==
    * HTTP_X_FORWARDED_FOR                                    : 194.214.30.201
    * HTTP_X_FORWARDED_PORT                                   : 443
    * HTTP_X_FORWARDED_PROTO                                  : https
    * HTTP_X_REQUESTED_WITH                                   : XMLHttpRequest
    * HTTP_X_REQUEST_ID                                       : 42e5ad54-86ac-4c04-b997-7c09687965a7
    * HTTP_X_REQUEST_START                                    : 1626342818873
    * ORIGINAL_FULLPATH                                       : /salles/libres.json?date=2022-001-21T09:00&id=&duree=4.0&formation_id=464&intervenant_id=445
    * ORIGINAL_SCRIPT_NAME                                    :
    * PATH_INFO                                               : /salles/libres.json
    * QUERY_STRING                                            : date=2022-001-21T09:00&id=&duree=4.0&formation_id=464&intervenant_id=445
    * REMOTE_ADDR                                             : 10.1.6.210
    * REQUEST_METHOD                                          : GET
    * REQUEST_PATH                                            : /salles/libres.json
    * REQUEST_URI                                             : /salles/libres.json?date=2022-001-21T09:00&id=&duree=4.0&formation_id=464&intervenant_id=445
    * ROUTES_14300_SCRIPT_NAME                                :
    * SCRIPT_NAME                                             :
    * SERVER_NAME                                             : planning.iae-paris.com
    * SERVER_PORT                                             : 443
    * SERVER_PROTOCOL                                         : HTTP/1.1
    * SERVER_SOFTWARE                                         : puma 4.3.8 Mysterious Traveller
    * action_controller.instance                              : #<SallesController:0x000055fcf404a528>
    * action_dispatch.authenticated_encrypted_cookie_salt     : authenticated encrypted cookie
    * action_dispatch.backtrace_cleaner                       : #<Rails::BacktraceCleaner:0x000055fcf12373e8>
    * action_dispatch.content_security_policy                 :
    * action_dispatch.content_security_policy_nonce_directives:
    * action_dispatch.content_security_policy_nonce_generator :
    * action_dispatch.content_security_policy_report_only     : false
    * action_dispatch.cookies                                 : #<ActionDispatch::Cookies::CookieJar:0x000055fcf401bd90>
    * action_dispatch.cookies_digest                          :
    * action_dispatch.cookies_rotations                       : #<ActiveSupport::Messages::RotationConfiguration:0x000055fceeb6ff58>
    * action_dispatch.cookies_same_site_protection            : #<Proc:0x000055fcf2fc3b50 /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/application.rb:629>
    * action_dispatch.cookies_serializer                      : json
    * action_dispatch.encrypted_cookie_cipher                 :
    * action_dispatch.encrypted_cookie_salt                   : encrypted cookie
    * action_dispatch.encrypted_signed_cookie_salt            : signed encrypted cookie
    * action_dispatch.http_auth_salt                          : http authentication
    * action_dispatch.key_generator                           : #<ActiveSupport::CachingKeyGenerator:0x000055fcf3269850>
    * action_dispatch.logger                                  : #<ActiveSupport::Logger:0x000055fceec99190>
    * action_dispatch.parameter_filter                        : [:password]
    * action_dispatch.permissions_policy                      :
    * action_dispatch.redirect_filter                         : []
    * action_dispatch.remote_ip                               : 194.214.30.201
    * action_dispatch.request.content_type                    : application/x-www-form-urlencoded
    * action_dispatch.request.formats                         : [#<Mime::Type:0x000055fceea9f998 @synonyms=["text/x-json", "application/jsonrequest"], @symbol=:json, @string="application/json", @hash=-2113649960876245115>]
    * action_dispatch.request.parameters                      : {"date"=>"2022-001-21T09:00", "id"=>"", "duree"=>"4.0", "formation_id"=>"464", "intervenant_id"=>"445", "controller"=>"salles", "action"=>"libres", "format"=>"json"}
    * action_dispatch.request.path_parameters                 : {:controller=>"salles", :action=>"libres", :format=>"json"}
    * action_dispatch.request.query_parameters                : {"date"=>"2022-001-21T09:00", "id"=>"", "duree"=>"4.0", "formation_id"=>"464", "intervenant_id"=>"445"}
    * action_dispatch.request.request_parameters              : {}
    * action_dispatch.request.unsigned_session_cookie         : {"session_id"=>"d4df56b4a7012523a73aa985a0a1e623", "view"=>"list", "filter"=>"all", "paginate"=>"all", "start_date"=>"2021-07-15", "warden.user.user.key"=>[[45], "$2a$10$5c0vO4sO1DmxkQPRxg47n."], "_csrf_token"=>"cfkNzdrEJAUeznyG4YScM564sMhME3cKmNjKGiOdDYI=", "formation"=>"MAE JB 2021 2022 GROUPE 2",...
    * action_dispatch.request_id                              : 42e5ad54-86ac-4c04-b997-7c09687965a7
    * action_dispatch.routes                                  : #<ActionDispatch::Routing::RouteSet:0x000055fcf29d1350>
    * action_dispatch.secret_key_base                         : d32ed58262eb5e7a69dc44de68438385b623cfbedeaec283ac06bf15529df6243d542ca99e152642fc36db48ecae5d64b47292cf5cea7192e95d52469b728983
    * action_dispatch.show_detailed_exceptions                : false
    * action_dispatch.show_exceptions                         : true
    * action_dispatch.signed_cookie_digest                    :
    * action_dispatch.signed_cookie_salt                      : signed cookie
    * action_dispatch.use_authenticated_cookie_encryption     : true
    * action_dispatch.use_cookies_with_metadata               : true
    * puma.config                                             : #<Puma::Configuration:0x000055fcee229c78>
    * puma.request_body_wait                                  : 0
    * puma.socket                                             : #<TCPSocket:0x000055fcf40acc78>
    * rack.after_reply                                        : []
    * rack.cors                                               : #<Rack::Cors::Result:0x000055fcf409a410>
    * rack.errors                                             : #<IO:0x000055fcedb27768>
    * rack.hijack                                             : #<Puma::Client:0x000055fcf40acc28>
    * rack.hijack?                                            : true
    * rack.input                                              : #<Puma::NullIO:0x000055fcee58a930>
    * rack.multiprocess                                       : false
    * rack.multithread                                        : true
    * rack.request.cookie_hash                                : {"_session_id"=>"LcVuHYzNVUSmULOzBCKSXShqYZ4TLAszNyopHfkoJ27dTrUk5FL7ZQRigdxH+mUl8+TYdMQLL5OeGrZS8Y1hliznC+7o7fMbb/ZFboTiVzyWccehL3cp3tDLTw9KHxVF9dVOhTOJXjG3GCE82JBqBskC0NNQDlI7kY/QDxhRxHE+bt9rxGGoF9f73skWH02bHSBbJqKUJ93VUopKR8ewL8E8mQyVFfuzMxDKxBHnsu29o5e9KfZW6LBhtD4TH7MTj/y3gRJST+asmGBQOagTr4t7KFa...
    * rack.request.cookie_string                              : _session_id=LcVuHYzNVUSmULOzBCKSXShqYZ4TLAszNyopHfkoJ27dTrUk5FL7ZQRigdxH%2BmUl8%2BTYdMQLL5OeGrZS8Y1hliznC%2B7o7fMbb%2FZFboTiVzyWccehL3cp3tDLTw9KHxVF9dVOhTOJXjG3GCE82JBqBskC0NNQDlI7kY%2FQDxhRxHE%2Bbt9rxGGoF9f73skWH02bHSBbJqKUJ93VUopKR8ewL8E8mQyVFfuzMxDKxBHnsu29o5e9KfZW6LBhtD4TH7MTj%2Fy3gRJST%2BasmGBQOagTr4t7KFaUjl6XPbgcICwR2%2FwkbjINsnibanTfBNs6vmpl2nI8%2FH0IvHRaHAVK0isX94fxnPPvObWrjrBK4aqFxr12pth3hwO8ok0m6qoaf31dkENCKSZVuyciBste1ShMBn3k5Oi1RaFqLrqbR3fl1OOFlH0rzubPH0uJuX3Xy0zGz%2FWgi3XRXKicXjIL%2Bt9Qcm%2F3fKSFyKT8Ueu92SrStYP82meIGyWm1bM66m%2BllwBGyfyWQZQ8kJehpFJ0A4khHCMbdZxg345W9sC54t7YAuwz7282fkz0wJwLjwv0FWLQTwMlaTm6PZdoptrh1UkKAKlIc%2BxmZRz9cLsApm45%2Fct4MGOGKsS9aBocvWq6BOCm0ghukh5nteSHuNXzWXlpyXFoX47KnDXrLWgw3blmDN8e--eCYg0PdM0%2FBXDCff--JBz3gHrieMDdewRBkpIShA%3D%3D; _ga=GA1.2.2089818695.1626342699; _gid=GA1.2.816376150.1626342699
    * rack.request.form_hash                                  : {}
    * rack.request.form_input                                 : #<Puma::NullIO:0x000055fcee58a930>
    * rack.request.form_vars                                  : [FILTERED]
    * rack.request.query_hash                                 : {"date"=>"2022-001-21T09:00", "id"=>"", "duree"=>"4.0", "formation_id"=>"464", "intervenant_id"=>"445"}
    * rack.request.query_string                               : date=2022-001-21T09:00&id=&duree=4.0&formation_id=464&intervenant_id=445
    * rack.run_once                                           : false
    * rack.session                                            : #<ActionDispatch::Request::Session:0x000055fcf407a020>
    * rack.session.options                                    : #<ActionDispatch::Request::Session::Options:0x000055fcf404bf68>
    * rack.tempfiles                                          : []
    * rack.url_scheme                                         : https
    * rack.version                                            : [1, 3]
    * warden                                                  : Warden::Proxy:2307880 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x000055fcf21d6f10>}

-------------------------------
Backtrace:
-------------------------------

  app/controllers/salles_controller.rb:167:in `parse'
  app/controllers/salles_controller.rb:167:in `libres'

**Comment by philippe-nougaillon** [comment]
Saisie d'une date a provoquer l'erreur : 2022-001-21
Il faut imposer l'emploi de Chrome pour avoir un calendrier ?
